name: Check Branch

on: pull_request

jobs:
  check-branch:
    runs-on:
      - engineering-runners-stg
    steps:
      - uses: actions/checkout@v4
      - run: node -v
      - run: sudo corepack enable
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm check-branch
